PACKAGE_NAME="hid-rapoo"
PACKAGE_VERSION="0.1"

MAKE="KVER=${kernelver} make all"
CLEAN="KVER=${kernelver} make clean"

BUILT_MODULE_NAME[0]="hid-rapoo"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
